[package]
name = "rok_derive"
version = "0.1.0"
authors = ["Eduard Stefes <eduard.stefes@gmail.com>"]

[lib]
proc-macro = true


[dependencies]
quote = "*"
proc-macro2 ="*"

[dependencies.syn]
version ="*"
features = ["extra-traits"]
